/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmHienThi.java
 *
 * Created on Jun 9, 2010, 2:10:09 PM
 */

package demoftp;

import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan
 */
public class frmHienThi extends javax.swing.JInternalFrame {
    private Socket socket;
    private PrintWriter out=null;
    private Scanner in=null;
    private String username;
    private String password;
    /** Creates new form frmHienThi */
    public frmHienThi(){
        initComponents();
    }
    public frmHienThi(String username,String password) {       
        initComponents();
        this.setTitle("Xin chào "+username);
        this.username=username;
        this.password=password;
        try{
                String data="";
                socket=new Socket(frmFTPClient.HOST,frmFTPClient.PORT);
                in=new Scanner(socket.getInputStream());
                out=new  PrintWriter(socket.getOutputStream(),true);
                out.println("file@username@password@");
                //data=in.nextLine().trim();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Lỗi", e.toString(),JOptionPane.ERROR_MESSAGE);
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setTitle("FTP Client");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
