/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddAWorkItem.java
 *
 * Created on Apr 3, 2011, 10:51:01 AM
 */

package GUI;

import Business._Total_CBBControler;
import Business.WorkItemModel;
import DataAccess.WorkItemData;
import Entity.Department;
import Entity.Location;
import Entity.Project;
import Entity.WorkItem;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nha.HV
 */
public class AddAWorkItem extends javax.swing.JDialog {
final SimpleDateFormat SDF = new SimpleDateFormat("MM/dd/yyyy");
    _Total_CBBControler   aawic;
    DefaultComboBoxModel    loccbbm;
    DefaultComboBoxModel    depcbb;
    DefaultComboBoxModel    prjcbb;
    Vector<Location>        lvec;
    Vector<Department>      dvec;
    Vector<Project>         pvec;
    Vector<Department>      dvecInLoc;
    
    //---
    WorkItem                wi;
    WorkItemData            widata;
    Vector<WorkItem>        wiVec;
    /** Creates new form AddAWorkItem */
    public AddAWorkItem(JFrame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        initdata();
        initform();
    }

 
    private void initdata(){
        aawic = new _Total_CBBControler();
       
        lvec = aawic.getlVec();
        pvec = aawic.getpVec();
        dvec = aawic.getdVec();
      

                aawic.setLcbbm(lvec);
                aawic.setPcbbm(pvec);
                for (Project prj : pvec) {
                    System.out.println(prj.getProjectName());

        }

                    loccbbm = aawic.getLcbbm();
                    prjcbb = aawic.getPcbbm();

    widata = new WorkItemData();
    wiVec = widata.getAllWorkItems();
    }

    private void initform(){
        jcbbaProj.setModel(prjcbb);
        jcbbaProj.setSelectedIndex(-1);
        jcbbLoc.setModel(loccbbm);
        jcbbLoc.setSelectedIndex(-1);
        jcbbaDept.setModel(new DefaultComboBoxModel());
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Tips: All work item must be in a time interval.");
      
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        jPanel3 = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jlbProject = new javax.swing.JLabel();
        jlbDepartment = new javax.swing.JLabel();
        jcbbaProj = new javax.swing.JComboBox();
        jcbbaDept = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        //SimpleDateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
        jdateStart = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jdateEnd = new com.toedter.calendar.JDateChooser();
        jcbbStatus = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtcancel = new javax.swing.JButton();
        jbtreset = new javax.swing.JButton();
        jBT_save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbbLoc = new javax.swing.JComboBox();
        jlbnotice = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtanotice = new javax.swing.JEditorPane();
        jXHeader2 = new org.jdesktop.swingx.JXHeader();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a work item");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Item Infomantions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 400));

        jlbName.setText("Department : ");

        jlbProject.setText("Project: ");

        jlbDepartment.setText("Status");

        jcbbaProj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbaProj.setKeySelectionManager(null);

        jcbbaDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbaDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbbaDeptMouseClicked(evt);
            }
        });
        jcbbaDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbaDeptActionPerformed(evt);
            }
        });
        jcbbaDept.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbbaDeptFocusGained(evt);
            }
        });

        jLabel1.setText("Start Date: ");

        jdateStart.setDateFormatString("MM/dd/yyyy");

        jLabel3.setText("End Date: ");

        jdateEnd.setDateFormatString("MM/dd/yyyy");

        jcbbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Started", "In Progress" }));

        jLabel2.setText("(mm/dd/yyyy)");
        jLabel2.setEnabled(false);

        jLabel4.setText("(mm/dd/yyyy)");
        jLabel4.setEnabled(false);

        jbtcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gnome-session-halt.png"))); // NOI18N
        jbtcancel.setText("Cancel");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        jbtreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/document-open-recent.png"))); // NOI18N
        jbtreset.setText("Reset");
        jbtreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtresetActionPerformed(evt);
            }
        });

        jBT_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/task-accepted.png"))); // NOI18N
        jBT_save.setText("Save");
        jBT_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_saveActionPerformed(evt);
            }
        });

        jLabel5.setText("Location: ");

        jcbbLoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbLoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbbLocItemStateChanged(evt);
            }
        });

        jlbnotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_16/dialog-information.png"))); // NOI18N
        jlbnotice.setLabelFor(jtanotice);
        jlbnotice.setText("Notice !");

        jScrollPane2.setBorder(null);

        jtanotice.setBackground(new java.awt.Color(255, 255, 204));
        jtanotice.setContentType("text/html");
        jtanotice.setEditable(false);
        jtanotice.setFont(new java.awt.Font("Tahoma", 0, 12));
        jScrollPane2.setViewportView(jtanotice);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(43, 43, 43)))
                            .addGap(293, 293, 293))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jlbDepartment)
                            .addGap(63, 63, 63)
                            .addComponent(jcbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(167, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jlbProject)
                            .addGap(53, 53, 53)
                            .addComponent(jcbbaProj, 0, 270, Short.MAX_VALUE)
                            .addGap(23, 23, 23))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jlbnotice)
                            .addContainerGap(330, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(47, 47, 47)
                                    .addComponent(jcbbLoc, 0, 270, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(94, 94, 94)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbbaDept, 0, 270, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jdateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jdateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)))))
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbtcancel)
                        .addGap(6, 6, 6)
                        .addComponent(jbtreset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBT_save)
                        .addGap(59, 59, 59))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbProject)
                            .addComponent(jcbbaProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jcbbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbName)
                            .addComponent(jcbbaDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jdateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbDepartment)
                            .addComponent(jcbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBT_save, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jlbnotice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        jXHeader2.setBackground(new java.awt.Color(204, 0, 0));
        jXHeader2.setBackgroundPainter(glossPainter1);
        jXHeader2.setTitle("Add a location");
        jXHeader2.setTitleFont(new java.awt.Font("Tahoma", 1, 18));
        jXHeader2.setTitleForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-445)/2, (screenSize.height-499)/2, 445, 499);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Do you want cancel?", "Do you want cancel?",JOptionPane.YES_NO_OPTION);
        if(i == 0){this.dispose();
        }
}//GEN-LAST:event_jbtcancelActionPerformed

    private void jbtresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtresetActionPerformed
    jcbbaDept.setSelectedIndex(-1);
    jcbbaProj.setSelectedIndex(-1);
    jdateStart.setDate(null);
    jdateEnd.setDate(null);
    jcbbStatus.setSelectedIndex(-1);
}//GEN-LAST:event_jbtresetActionPerformed

    private void jBT_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_saveActionPerformed
    if(jcbbaDept.getSelectedIndex() == -1){
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Department can not be empty !");
        return;
    }
    if(jcbbaProj.getSelectedIndex() == -1){
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Project can not be empty !");
        return;
    }
    if(jcbbStatus.getSelectedIndex() == -1){
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Status can not be empty !");
        return;
    }
    if(jdateStart.getDate() == null){
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Start date cannot be empty!");
        return;
    }
    if(jdateEnd.getDate() == null){
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: End date cannot be empty!");
        return;
    }

    if(jdateEnd.getDate().compareTo(jdateStart.getDate()) < 0){
         jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: End date cannot be later than StartDate !");
        return;
    }

    if(jcbbStatus.getSelectedIndex() == 0){
        Date today = new Date();

        if(jdateStart.getDate().compareTo(today) < 0){
            jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Start date cannot set past date !");
        return;
        }
    }

    jtanotice.setText(null);
    //Set infomation to add;
    int PrjID = pvec.get(jcbbaProj.getSelectedIndex()).getProjectID();
    int DepID = dvecInLoc.get(jcbbaDept.getSelectedIndex()).getDepartmentID();
    
    
    wi = new WorkItem();
    wi.setDepartmentID(DepID);
    wi.setProjectID(PrjID);
    wi.setStartDate(jdateStart.getDate());
    wi.setEndDate(jdateEnd.getDate());
    wi.setStatus(jcbbStatus.getSelectedItem().toString());
    
    widata = new WorkItemData();
 //
    int add = widata.addAWorkItem(wi);
    if(add == 1){
        JOptionPane.showMessageDialog(null, "Added Successful");
        this.dispose();
        return;
      
        }
     if (add == -1) {
            if(checkConfictWorkItems(wi)){
                return;
            }
    }
 else{
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Error: Cannot add this work item (Unkown issue) ");
 }

    }//GEN-LAST:event_jBT_saveActionPerformed

    private void jcbbaDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbaDeptActionPerformed
     
    }//GEN-LAST:event_jcbbaDeptActionPerformed

    private void jcbbaDeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbbaDeptMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jcbbaDeptMouseClicked

    private void jcbbaDeptFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbbaDeptFocusGained
        // TODO add your handling code here:
        if(jcbbLoc.getSelectedIndex() == -1){
            jtanotice.setText("Warning : You must chose a Location first!");
        }
        return;
    }//GEN-LAST:event_jcbbaDeptFocusGained
    private void jcbbLocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbbLocItemStateChanged
        // TODO add your handling code here:
        if(jcbbLoc.getSelectedIndex() > -1){
            jtanotice.setText(null);
            
            //<<<<<<< GET ID FROM COMMBO BOX >>>>>>>
            int locID = lvec.get(jcbbLoc.getSelectedIndex()).getLocationID();

            dvecInLoc = new Vector<Department>();
            for (Department d: dvec) {
                if(d.getLocationID() == locID){
                    dvecInLoc.add(d);
              
                }
            }
            aawic.setDcbbm(dvecInLoc);
            if(aawic.getDcbbm().getSize() == 0){
              jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >There is no deparntment in this location.\n You need create Location first!");
              jcbbaDept.setModel(new DefaultComboBoxModel());
              return;
            }else{
            jtanotice.setText("<font face=\"Tahoma\" size =\"3\" >Tips: Chose a Depatment to add work items!");
            jcbbaDept.setModel(aawic.getDcbbm());
        }

        }
    }//GEN-LAST:event_jcbbLocItemStateChanged

       private boolean checkConfictWorkItems(WorkItem wi) {
        if(jcbbaProj.getSelectedIndex() != -1 && jcbbaDept.getSelectedIndex() != -1){
        Vector<WorkItem> conflickVector = new Vector<WorkItem>();
        jtanotice.setFont(new java.awt.Font("Tahoma", 0, 12));
        jtanotice.setText("<font face=\"Tahoma\" size =\"3\" > Confict! (Check on Work Item table) <b>");
        conflickVector = new WorkItemData().checkConfictWorkItems(wi);
        if(conflickVector == null){
            return false;
        }else{
            jtanotice.setFont(new java.awt.Font("Tahoma", 0, 12));
            jtanotice.setText("<font face=\"Tahoma\" size =\"3\" > Confict! (Check on Work Item table) <b>");
           return true;
        } 
     }
        return false;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             

               
                AddAWorkItem dialog = new AddAWorkItem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JButton jBT_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXHeader jXHeader2;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JButton jbtreset;
    private javax.swing.JComboBox jcbbLoc;
    private javax.swing.JComboBox jcbbStatus;
    private javax.swing.JComboBox jcbbaDept;
    private javax.swing.JComboBox jcbbaProj;
    private com.toedter.calendar.JDateChooser jdateEnd;
    private com.toedter.calendar.JDateChooser jdateStart;
    private javax.swing.JLabel jlbDepartment;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbProject;
    private javax.swing.JLabel jlbnotice;
    private javax.swing.JEditorPane jtanotice;
    // End of variables declaration//GEN-END:variables

}
