/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Mainfrm.java
 *
 * Created on Nov 17, 2011, 9:34:29 PM
 */
package baitap;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Lovely
 */
public  class Mainfrm extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;



 List<Student> student = new ArrayList<Student>();
        StudentManage man = new StudentManage();
        int idx,last,type=1;
        List<Student> tmp =  new ArrayList<Student>();
        List<Student>   st= new ArrayList<Student>();
        String txtKey,khoa;
         StudentModel svtbm;
         int pb=0;
    /** Creates new form Mainfrm */
    public Mainfrm() {
     
        initComponents();



       loaddb();
       tclear();
    }
    public Mainfrm(String khoa) {
     
        initComponents();

       loaddb();
       tclear();
      this.khoa=khoa;
      Khoa.setText(khoa);
    }
public void loaddb(){
if(pb>0){
    Vector<Student> sm= new Vector<Student>();
       int i=0; 

       
    for (;i<student.size();i++) 
    {
   if(student.get(i).getKhoa().contains(khoa)) {    sm.add(student.get(i));}
      
     }   
   
 svtbm=new StudentModel(sm);
jTable2.setModel(svtbm);

}
pb=pb+1;
}
public void tclear(){
//System.out.print(khoa);
Hoten.setText("");
Lop.setText("");
Khoa.setText(khoa);
NS.setText("");
TB1.setText("");
TB2.setText("");
TB3.setText("");
TB4.setText("");
TB5.setText("");
TB6.setText("");
TB7.setText("");
TB8.setText("");
TN1.setText("");
TN2.setText("");
TN3.setText("");
TN4.setText("");
TN5.setText("");
TN6.setText("");
TN7.setText("");
TN8.setText("");
N1.setText("");
N2.setText("");
N3.setText("");
N4.setText("");
N5.setText("");
N6.setText("");
N7.setText("");
N8.setText("");
R1.setText("");
R2.setText("");
R3.setText("");
R4.setText("");
R5.setText("");
R6.setText("");
R7.setText("");
R8.setText("");
vpchk.setSelected(false);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnlMan = new javax.swing.JTabbedPane();
        jpnladd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Hoten = new javax.swing.JTextField();
        NS = new javax.swing.JTextField();
        Lop = new javax.swing.JTextField();
        TB1 = new javax.swing.JTextField();
        TB2 = new javax.swing.JTextField();
        TB3 = new javax.swing.JTextField();
        TB4 = new javax.swing.JTextField();
        TB5 = new javax.swing.JTextField();
        TB6 = new javax.swing.JTextField();
        TB7 = new javax.swing.JTextField();
        TB8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vpchk = new javax.swing.JCheckBox();
        Khoa = new javax.swing.JLabel();
        R8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        R7 = new javax.swing.JTextField();
        R6 = new javax.swing.JTextField();
        R5 = new javax.swing.JTextField();
        R4 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        N3 = new javax.swing.JTextField();
        N4 = new javax.swing.JTextField();
        N5 = new javax.swing.JTextField();
        N6 = new javax.swing.JTextField();
        N7 = new javax.swing.JTextField();
        N8 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        TN1 = new javax.swing.JTextField();
        TN2 = new javax.swing.JTextField();
        TN3 = new javax.swing.JTextField();
        TN4 = new javax.swing.JTextField();
        TN5 = new javax.swing.JTextField();
        TN6 = new javax.swing.JTextField();
        TN7 = new javax.swing.JTextField();
        TN8 = new javax.swing.JTextField();
        jpnlSearch = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rbTen = new javax.swing.JRadioButton();
        rbKhoa = new javax.swing.JRadioButton();
        rbLoai = new javax.swing.JRadioButton();
        rbLop = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jpnlView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlMan.setPreferredSize(new java.awt.Dimension(800, 600));

        jpnladd.setPreferredSize(new java.awt.Dimension(800, 600));
        jpnladd.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Thêm Sinh Viên");
        jpnladd.add(jLabel2);
        jLabel2.setBounds(403, 11, 107, 17);

        jLabel4.setText("Họ Tên");
        jpnladd.add(jLabel4);
        jLabel4.setBounds(110, 115, 34, 14);

        jLabel5.setText("Ngày sinh");
        jpnladd.add(jLabel5);
        jLabel5.setBounds(110, 141, 47, 14);

        jLabel6.setText("Lớp");
        jpnladd.add(jLabel6);
        jLabel6.setBounds(110, 89, 17, 14);

        jLabel7.setText("Khoa");
        jpnladd.add(jLabel7);
        jLabel7.setBounds(110, 60, 24, 14);

        jLabel8.setText("TB Kỳ 1");
        jpnladd.add(jLabel8);
        jLabel8.setBounds(110, 164, 47, 14);

        jLabel9.setText("TB Kỳ 2");
        jpnladd.add(jLabel9);
        jLabel9.setBounds(110, 190, 47, 14);

        jLabel10.setText("TB Kỳ 3");
        jpnladd.add(jLabel10);
        jLabel10.setBounds(110, 216, 47, 14);

        jLabel11.setText("TB Kỳ 6");
        jpnladd.add(jLabel11);
        jLabel11.setBounds(110, 294, 36, 14);

        jLabel12.setText("TB Kỳ 5");
        jpnladd.add(jLabel12);
        jLabel12.setBounds(110, 268, 36, 14);

        jLabel13.setText("TB Kỳ 4");
        jpnladd.add(jLabel13);
        jLabel13.setBounds(110, 242, 36, 14);

        jLabel15.setText("TB Kỳ 8");
        jpnladd.add(jLabel15);
        jLabel15.setBounds(110, 346, 36, 17);

        jLabel16.setText("TB Kỳ 7");
        jpnladd.add(jLabel16);
        jLabel16.setBounds(110, 320, 36, 14);
        jpnladd.add(Hoten);
        Hoten.setBounds(300, 112, 210, 20);
        jpnladd.add(NS);
        NS.setBounds(300, 138, 130, 20);
        jpnladd.add(Lop);
        Lop.setBounds(300, 86, 140, 20);
        jpnladd.add(TB1);
        TB1.setBounds(224, 164, 40, 20);
        jpnladd.add(TB2);
        TB2.setBounds(224, 190, 40, 20);
        jpnladd.add(TB3);
        TB3.setBounds(224, 216, 40, 20);
        jpnladd.add(TB4);
        TB4.setBounds(224, 242, 40, 20);
        jpnladd.add(TB5);
        TB5.setBounds(224, 268, 40, 20);
        jpnladd.add(TB6);
        TB6.setBounds(224, 294, 40, 20);
        jpnladd.add(TB7);
        TB7.setBounds(224, 320, 40, 20);
        jpnladd.add(TB8);
        TB8.setBounds(224, 346, 40, 20);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpnladd.add(jButton1);
        jButton1.setBounds(395, 414, 59, 23);

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpnladd.add(jButton2);
        jButton2.setBounds(485, 414, 51, 23);

        vpchk.setText("Đã vi phạm qui chế thi");
        jpnladd.add(vpchk);
        vpchk.setBounds(200, 384, 131, 23);
        jpnladd.add(Khoa);
        Khoa.setBounds(300, 60, 140, 20);
        jpnladd.add(R8);
        R8.setBounds(411, 346, 40, 20);

        jLabel22.setText("Rèn luyện 8");
        jpnladd.add(jLabel22);
        jLabel22.setBounds(306, 346, 57, 17);

        jLabel33.setText("Rèn luyện 7");
        jpnladd.add(jLabel33);
        jLabel33.setBounds(306, 320, 57, 14);

        jLabel34.setText("Rèn luyện 6");
        jpnladd.add(jLabel34);
        jLabel34.setBounds(306, 294, 57, 14);
        jpnladd.add(R7);
        R7.setBounds(411, 320, 40, 20);
        jpnladd.add(R6);
        R6.setBounds(411, 294, 40, 20);
        jpnladd.add(R5);
        R5.setBounds(411, 268, 40, 20);
        jpnladd.add(R4);
        R4.setBounds(411, 242, 40, 20);
        jpnladd.add(R3);
        R3.setBounds(411, 216, 40, 20);
        jpnladd.add(R2);
        R2.setBounds(411, 190, 40, 20);
        jpnladd.add(R1);
        R1.setBounds(411, 164, 40, 20);

        jLabel35.setText("Rèn luyện 1");
        jpnladd.add(jLabel35);
        jLabel35.setBounds(306, 164, 72, 14);

        jLabel36.setText("Rèn luyện 2");
        jpnladd.add(jLabel36);
        jLabel36.setBounds(306, 190, 101, 14);

        jLabel37.setText("Rèn luyện 3");
        jpnladd.add(jLabel37);
        jLabel37.setBounds(306, 216, 101, 14);

        jLabel38.setText("Rèn luyện 4");
        jpnladd.add(jLabel38);
        jLabel38.setBounds(306, 242, 57, 14);

        jLabel39.setText("Rèn luyện 5");
        jpnladd.add(jLabel39);
        jLabel39.setBounds(306, 268, 57, 14);

        jLabel40.setText("Nợ môn 8");
        jpnladd.add(jLabel40);
        jLabel40.setBounds(519, 346, 45, 17);

        jLabel41.setText("Nợ môn 7");
        jpnladd.add(jLabel41);
        jLabel41.setBounds(519, 320, 45, 14);

        jLabel42.setText("Nợ môn 6");
        jpnladd.add(jLabel42);
        jLabel42.setBounds(519, 294, 45, 14);

        jLabel43.setText("Nợ môn 5");
        jpnladd.add(jLabel43);
        jLabel43.setBounds(519, 268, 45, 14);

        jLabel44.setText("Nợ môn 4");
        jpnladd.add(jLabel44);
        jLabel44.setBounds(519, 242, 45, 14);

        jLabel45.setText("Nợ môn 3");
        jpnladd.add(jLabel45);
        jLabel45.setBounds(519, 216, 115, 14);

        jLabel46.setText("Nợ môn 2");
        jpnladd.add(jLabel46);
        jLabel46.setBounds(519, 190, 115, 14);

        jLabel47.setText("Nợ môn 1");
        jpnladd.add(jLabel47);
        jLabel47.setBounds(519, 164, 73, 14);
        jpnladd.add(N1);
        N1.setBounds(638, 164, 40, 20);
        jpnladd.add(N2);
        N2.setBounds(638, 190, 40, 20);
        jpnladd.add(N3);
        N3.setBounds(638, 216, 40, 20);
        jpnladd.add(N4);
        N4.setBounds(638, 242, 40, 20);
        jpnladd.add(N5);
        N5.setBounds(638, 268, 40, 20);
        jpnladd.add(N6);
        N6.setBounds(638, 294, 40, 20);
        jpnladd.add(N7);
        N7.setBounds(638, 320, 40, 20);
        jpnladd.add(N8);
        N8.setBounds(638, 346, 40, 20);

        jLabel48.setText("Trả nợ 8");
        jpnladd.add(jLabel48);
        jLabel48.setBounds(738, 346, 40, 17);

        jLabel49.setText("Trả nợ 7");
        jpnladd.add(jLabel49);
        jLabel49.setBounds(738, 320, 40, 14);

        jLabel50.setText("Trả nợ 6");
        jpnladd.add(jLabel50);
        jLabel50.setBounds(738, 294, 40, 14);

        jLabel51.setText("Trả nợ 5");
        jpnladd.add(jLabel51);
        jLabel51.setBounds(738, 268, 40, 14);

        jLabel52.setText("Trả nợ 4");
        jpnladd.add(jLabel52);
        jLabel52.setBounds(738, 242, 40, 14);

        jLabel53.setText("Trả nợ 3");
        jpnladd.add(jLabel53);
        jLabel53.setBounds(738, 216, 56, 14);

        jLabel54.setText("Trả nợ 2");
        jpnladd.add(jLabel54);
        jLabel54.setBounds(738, 190, 40, 14);

        jLabel55.setText("Trả nợ 1");
        jpnladd.add(jLabel55);
        jLabel55.setBounds(738, 164, 56, 14);
        jpnladd.add(TN1);
        TN1.setBounds(843, 164, 40, 20);
        jpnladd.add(TN2);
        TN2.setBounds(843, 190, 40, 20);
        jpnladd.add(TN3);
        TN3.setBounds(843, 216, 40, 20);
        jpnladd.add(TN4);
        TN4.setBounds(843, 242, 40, 20);
        jpnladd.add(TN5);
        TN5.setBounds(843, 268, 40, 20);
        jpnladd.add(TN6);
        TN6.setBounds(843, 294, 40, 20);
        jpnladd.add(TN7);
        TN7.setBounds(843, 320, 40, 20);
        jpnladd.add(TN8);
        TN8.setBounds(843, 346, 40, 20);

        jpnlMan.addTab("Thêm", jpnladd);

        jLabel14.setText("Từ khóa");

        jButton3.setText("Tìm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel31.setText("Tìm kiếm");

        jLabel32.setText("Theo");

        buttonGroup1.add(rbTen);
        rbTen.setText("Họ tên");

        buttonGroup1.add(rbKhoa);
        rbKhoa.setText("Khoa");

        buttonGroup1.add(rbLoai);
        rbLoai.setText("Loại");

        buttonGroup1.add(rbLop);
        rbLop.setText("Lớp");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Luận văn");

        org.jdesktop.layout.GroupLayout jpnlSearchLayout = new org.jdesktop.layout.GroupLayout(jpnlSearch);
        jpnlSearch.setLayout(jpnlSearchLayout);
        jpnlSearchLayout.setHorizontalGroup(
            jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlSearchLayout.createSequentialGroup()
                .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(363, 363, 363)
                        .add(jLabel31))
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(211, 211, 211)
                        .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpnlSearchLayout.createSequentialGroup()
                                .add(jLabel14)
                                .add(18, 18, 18)
                                .add(key, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jpnlSearchLayout.createSequentialGroup()
                                .add(jLabel32)
                                .add(36, 36, 36)
                                .add(rbTen)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(rbLop)
                                .add(10, 10, 10)
                                .add(rbKhoa)
                                .add(18, 18, 18)
                                .add(rbLoai)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jRadioButton1))))
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 893, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(341, 341, 341)
                        .add(jButton3)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jpnlSearchLayout.setVerticalGroup(
            jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlSearchLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jLabel31)
                .add(18, 18, 18)
                .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jLabel14))
                    .add(key, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(rbLop)
                                .add(rbKhoa)
                                .add(rbTen))
                            .add(jpnlSearchLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(rbLoai)
                                .add(jRadioButton1))))
                    .add(jpnlSearchLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel32)))
                .add(7, 7, 7)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .add(38, 38, 38))
        );

        jpnlMan.addTab("Tìm kiếm", jpnlSearch);

        jLabel1.setText("Danh sách sinh viên");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        org.jdesktop.layout.GroupLayout jpnlViewLayout = new org.jdesktop.layout.GroupLayout(jpnlView);
        jpnlView.setLayout(jpnlViewLayout);
        jpnlViewLayout.setHorizontalGroup(
            jpnlViewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlViewLayout.createSequentialGroup()
                .add(jpnlViewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlViewLayout.createSequentialGroup()
                        .add(281, 281, 281)
                        .add(jLabel1))
                    .add(jpnlViewLayout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnlViewLayout.setVerticalGroup(
            jpnlViewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlViewLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .add(44, 44, 44))
        );

        jpnlMan.addTab("Danh sách", jpnlView);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(800, 21));

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Đọc dữ liệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Lưu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setText("Thoát");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Khoa");

        jMenuItem3.setText("Chọn Khoa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Trợ giúp");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlMan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1024, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlMan, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
                man.db(student,1);
                  loaddb();   
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mainfrm.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    try {
            // TODO add your handling code here:
                student=man.db(student,0);
                loaddb();     
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mainfrm.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    // TODO add your handling code here:
        ChonKhoa m = new ChonKhoa();
    m.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    if(rbTen.isSelected()){type=1;}else
        if(rbLop.isSelected()){type=2;}else
            if(rbKhoa.isSelected()){type=3;}else 
                if(rbKhoa.isSelected()){type=4;}else {type=5;}
    txtKey=key.getText();
    st=man.Search(type,txtKey,student);
    Vector<Student> sm= new Vector<Student>();
    int i=0;

    for (;i<st.size();i++) {
        sm.add(st.get(i));

    }
    svtbm=new StudentModel(sm);
    jTable1.setModel(svtbm);
    loaddb();
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    tclear();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    String bl;
    Student stu=new Student();
    stu.setHoten( Hoten.getText());
    stu.setKhoa(khoa);
    stu.setLop(Lop.getText());
    stu.setDateBirth(NS.getText().trim());
    stu.setDk1(Float.parseFloat(TB1.getText()));

    stu.setDk2(Float.parseFloat(TB2.getText()));

    stu.setDk3(Float.parseFloat(TB3.getText()));

    stu.setDk4(Float.parseFloat(TB4.getText()));

    stu.setDk5(Float.parseFloat(TB5.getText()));

    stu.setDk6(Float.parseFloat(TB6.getText()));

    stu.setDk7(Float.parseFloat(TB7.getText()));

    stu.setDk8(Float.parseFloat(TB8.getText()));

    stu.setR1(Float.parseFloat(TB1.getText()));

    stu.setR2(Float.parseFloat(TB2.getText()));

    stu.setR3(Float.parseFloat(TB3.getText()));

    stu.setR4(Float.parseFloat(TB4.getText()));

    stu.setR5(Float.parseFloat(TB5.getText()));

    stu.setR6(Float.parseFloat(TB6.getText()));

    stu.setR7(Float.parseFloat(TB7.getText()));

    stu.setR8(Float.parseFloat(TB8.getText()));


    stu.setNo1(Integer.parseInt(N1.getText()));
    stu.setNo2(Integer.parseInt(N2.getText()));
    stu.setNo3(Integer.parseInt(N3.getText()));
    stu.setNo4(Integer.parseInt(N4.getText()));
    stu.setNo5(Integer.parseInt(N5.getText()));
    stu.setNo6(Integer.parseInt(N6.getText()));
    stu.setNo7(Integer.parseInt(N7.getText()));
    stu.setNo8(Integer.parseInt(N8.getText()));

    stu.setTra1(Integer.parseInt(TN1.getText()));
    stu.setTra2(Integer.parseInt(TN2.getText()));
    stu.setTra3(Integer.parseInt(TN3.getText()));
    stu.setTra4(Integer.parseInt(TN4.getText()));
    stu.setTra5(Integer.parseInt(TN5.getText()));
    stu.setTra6(Integer.parseInt(TN6.getText()));
    stu.setTra7(Integer.parseInt(TN7.getText()));
    stu.setTra8(Integer.parseInt(TN8.getText()));
    if(student.isEmpty()) {
        last = 0;} else{
        last = student.get(student.size()-1).getId();
        }
    last++;
    Student s =new Student();
    StudentManage man1 = new StudentManage();
    try {
        if(vpchk.isSelected()){bl="co";}else{bl="khong";}
        stu.setVipham(bl);
        s=man1.addStudent(last,stu);
        student.add(student.size(),s);
    } catch (ParseException ex) {
        Logger.getLogger(Mainfrm.class.getName()).log(Level.SEVERE, null, ex);
    }
    stu.setLV("có");
    tclear();
    loaddb();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Mainfrm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hoten;
    private javax.swing.JLabel Khoa;
    private javax.swing.JTextField Lop;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField N2;
    private javax.swing.JTextField N3;
    private javax.swing.JTextField N4;
    private javax.swing.JTextField N5;
    private javax.swing.JTextField N6;
    private javax.swing.JTextField N7;
    private javax.swing.JTextField N8;
    private javax.swing.JTextField NS;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JTextField R4;
    private javax.swing.JTextField R5;
    private javax.swing.JTextField R6;
    private javax.swing.JTextField R7;
    private javax.swing.JTextField R8;
    private javax.swing.JTextField TB1;
    private javax.swing.JTextField TB2;
    private javax.swing.JTextField TB3;
    private javax.swing.JTextField TB4;
    private javax.swing.JTextField TB5;
    private javax.swing.JTextField TB6;
    private javax.swing.JTextField TB7;
    private javax.swing.JTextField TB8;
    private javax.swing.JTextField TN1;
    private javax.swing.JTextField TN2;
    private javax.swing.JTextField TN3;
    private javax.swing.JTextField TN4;
    private javax.swing.JTextField TN5;
    private javax.swing.JTextField TN6;
    private javax.swing.JTextField TN7;
    private javax.swing.JTextField TN8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTabbedPane jpnlMan;
    private javax.swing.JPanel jpnlSearch;
    private javax.swing.JPanel jpnlView;
    private javax.swing.JPanel jpnladd;
    private javax.swing.JTextField key;
    private javax.swing.JRadioButton rbKhoa;
    private javax.swing.JRadioButton rbLoai;
    private javax.swing.JRadioButton rbLop;
    private javax.swing.JRadioButton rbTen;
    private javax.swing.JCheckBox vpchk;
    // End of variables declaration//GEN-END:variables
}
