/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestTransfer.java
 *
 * Created on Apr 2, 2011, 11:08:24 PM
 */

package GUI;

import Business.*;
import Entity.*;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author Lovely
 */
public class RequestTransfer extends javax.swing.JFrame {
private TransferManagement tm = new TransferManagement();
private LocationComboboxControler  lm = new LocationComboboxControler();
private DepartmentComboBoxControler  dcbc = new DepartmentComboBoxControler();
private ProjectComboBoxControler  pcbc = new ProjectComboBoxControler();
private RoleComboBoxControler rm = new RoleComboBoxControler();
private EmployeeManager em = new EmployeeManager();
private TransferModel tmo = new TransferModel();
public Employee emp = new Employee();
    /** Creates new form RequestTransfer */

    public RequestTransfer() {
      
        initComponents();
       setTable(emp);
       EmployeeModel emod = em.getAllEmployee();
        DefaultComboBoxModel dcbm = new  DefaultComboBoxModel();
        for(int i=0;i<emod.getRowCount();i++){
        dcbm.addElement(emod.getEmployeeAt(i).getUsername());
        }
        cbbUserName.setModel(dcbm);

    }
private void setTable(Employee e) {

     tblHistory.setModel(tm.getAllTransferByEmpID(e.getEmployeeID()));

        tblHistory.setFillsViewportHeight(true);
        tblHistory.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(12).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(13).setPreferredWidth(60);


         tblLastReq.setModel(tm.getLastTransferByEmpID(e.getEmployeeID()));


        tblLastReq.setFillsViewportHeight(true);
        tblLastReq.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblLastReq.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblLastReq.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblLastReq.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(12).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(13).setPreferredWidth(60);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRequest = new javax.swing.JPanel();
        TblPaneFeature = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlUpdate1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jtf_EmployeeID = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jcb_FrmDep = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jcb_ToDep = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jcb_FrLoc = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jcb_Toloc = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jcb_FrPro = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jcb_ToPro = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jtf_Allowance = new javax.swing.JTextField();
        jbtnUp1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDc_Join = new com.toedter.calendar.JDateChooser();
        jDc_Rel = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ReportMan = new javax.swing.JTextField();
        tf_CreateDate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pnlUpdate2 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jtxtCodenameUpd2 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jtxtNameUpd2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jcmbFdepUpd2 = new javax.swing.JComboBox();
        jLabel57 = new javax.swing.JLabel();
        jcmbTodepUpd2 = new javax.swing.JComboBox();
        jLabel58 = new javax.swing.JLabel();
        jcmbFlocUpd2 = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        jcmbTolocUpd2 = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        jcmbFproUpd2 = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();
        jcmbToproUpd2 = new javax.swing.JComboBox();
        jLabel62 = new javax.swing.JLabel();
        jtxtJoindateUpd2 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jtxtReldateUpd2 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jtxtAllowanceUpd2 = new javax.swing.JTextField();
        jbtnUp2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jpnlHistory1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jpnlMessage1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLastReq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbbUserName = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTransReq = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcontent = new javax.swing.JTextArea();
        btnAppr = new javax.swing.JButton();
        btnDeni = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        pnlRequest.setPreferredSize(new java.awt.Dimension(790, 510));

        javax.swing.GroupLayout pnlRequestLayout = new javax.swing.GroupLayout(pnlRequest);
        pnlRequest.setLayout(pnlRequestLayout);
        pnlRequestLayout.setHorizontalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        pnlRequestLayout.setVerticalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new java.awt.FlowLayout());

        TblPaneFeature.setPreferredSize(new java.awt.Dimension(800, 600));
        TblPaneFeature.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TblPaneFeatureStateChanged(evt);
            }
        });

        pnlUpdate1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        pnlUpdate1.setPreferredSize(new java.awt.Dimension(500, 33));
        pnlUpdate1.setLayout(null);

        jLabel33.setText("Employee Identity:");
        jLabel33.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel33);
        jLabel33.setBounds(13, 49, 100, 14);

        jtf_EmployeeID.setEnabled(false);
        jtf_EmployeeID.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate1.add(jtf_EmployeeID);
        jtf_EmployeeID.setBounds(118, 47, 170, 19);

        jLabel35.setText("Employee Name:");
        jLabel35.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel35);
        jLabel35.setBounds(338, 49, 100, 14);

        tf_name.setEditable(false);
        tf_name.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate1.add(tf_name);
        tf_name.setBounds(450, 50, 170, 19);

        jLabel37.setText("From Department:");
        jLabel37.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel37);
        jLabel37.setBounds(10, 90, 100, 14);

        jcb_FrmDep.setEnabled(false);
        jcb_FrmDep.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate1.add(jcb_FrmDep);
        jcb_FrmDep.setBounds(120, 90, 170, 22);

        jLabel39.setText("To Department:");
        jLabel39.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel39);
        jLabel39.setBounds(340, 100, 100, 14);

        jcb_ToDep.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate1.add(jcb_ToDep);
        jcb_ToDep.setBounds(450, 90, 170, 22);

        jLabel41.setText("From Location:");
        jLabel41.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel41);
        jLabel41.setBounds(10, 130, 100, 14);

        jcb_FrLoc.setEnabled(false);
        jcb_FrLoc.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate1.add(jcb_FrLoc);
        jcb_FrLoc.setBounds(120, 130, 170, 22);

        jLabel43.setText("To Location:");
        jLabel43.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel43);
        jLabel43.setBounds(340, 140, 100, 14);

        jcb_Toloc.setPreferredSize(new java.awt.Dimension(170, 22));
        jcb_Toloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_TolocActionPerformed(evt);
            }
        });
        pnlUpdate1.add(jcb_Toloc);
        jcb_Toloc.setBounds(450, 130, 170, 22);

        jLabel45.setText("From Project:");
        jLabel45.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel45);
        jLabel45.setBounds(10, 170, 100, 14);

        jcb_FrPro.setEnabled(false);
        jcb_FrPro.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate1.add(jcb_FrPro);
        jcb_FrPro.setBounds(120, 170, 170, 22);

        jLabel47.setText("To Project:");
        jLabel47.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel47);
        jLabel47.setBounds(340, 180, 100, 14);

        jcb_ToPro.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate1.add(jcb_ToPro);
        jcb_ToPro.setBounds(450, 170, 170, 22);

        jLabel49.setText("Join Date:");
        jLabel49.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel49);
        jLabel49.setBounds(10, 210, 100, 14);

        jLabel51.setText("Relieve Date:");
        jLabel51.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate1.add(jLabel51);
        jLabel51.setBounds(340, 220, 100, 14);

        jLabel4.setPreferredSize(new java.awt.Dimension(100, 1));
        pnlUpdate1.add(jLabel4);
        jLabel4.setBounds(518, 241, 100, 1);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Total Allowance:       ");
        jLabel53.setPreferredSize(new java.awt.Dimension(215, 14));
        pnlUpdate1.add(jLabel53);
        jLabel53.setBounds(10, 280, 100, 14);

        jtf_Allowance.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate1.add(jtf_Allowance);
        jtf_Allowance.setBounds(120, 280, 170, 19);

        jbtnUp1.setText("Request");
        jbtnUp1.setOpaque(false);
        jbtnUp1.setPreferredSize(new java.awt.Dimension(100, 30));
        pnlUpdate1.add(jbtnUp1);
        jbtnUp1.setBounds(260, 340, 100, 30);

        jButton1.setText("Cancel");
        pnlUpdate1.add(jButton1);
        jButton1.setBounds(380, 340, 100, 30);

        jDc_Join.setEnabled(false);
        pnlUpdate1.add(jDc_Join);
        jDc_Join.setBounds(120, 210, 170, 20);
        pnlUpdate1.add(jDc_Rel);
        jDc_Rel.setBounds(450, 210, 170, 20);

        jLabel2.setText("Reporting Manager:");
        pnlUpdate1.add(jLabel2);
        jLabel2.setBounds(340, 260, 110, 14);

        jLabel3.setText("Creation Date:");
        pnlUpdate1.add(jLabel3);
        jLabel3.setBounds(10, 250, 71, 14);

        tf_ReportMan.setEditable(false);
        pnlUpdate1.add(tf_ReportMan);
        tf_ReportMan.setBounds(450, 260, 170, 20);

        tf_CreateDate.setEditable(false);
        pnlUpdate1.add(tf_CreateDate);
        tf_CreateDate.setBounds(120, 250, 170, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        TblPaneFeature.addTab("Request", jPanel1);

        pnlUpdate2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Information"));
        pnlUpdate2.setPreferredSize(new java.awt.Dimension(500, 33));
        pnlUpdate2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setText("Code Name:");
        jLabel54.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, -1, -1));

        jtxtCodenameUpd2.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate2.add(jtxtCodenameUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 47, -1, -1));

        jLabel55.setText("Name:");
        jLabel55.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 49, -1, -1));

        jtxtNameUpd2.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate2.add(jtxtNameUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel56.setText("From Department:");
        jLabel56.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jcmbFdepUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbFdepUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel57.setText("To Department:");
        jLabel57.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jcmbTodepUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbTodepUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jLabel58.setText("From Location:");
        jLabel58.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jcmbFlocUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbFlocUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel59.setText("To Location:");
        jLabel59.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jcmbTolocUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbTolocUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel60.setText("From Project:");
        jLabel60.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jcmbFproUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbFproUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel61.setText("To Project:");
        jLabel61.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jcmbToproUpd2.setPreferredSize(new java.awt.Dimension(170, 22));
        pnlUpdate2.add(jcmbToproUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel62.setText("Join Date:");
        jLabel62.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jtxtJoindateUpd2.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate2.add(jtxtJoindateUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel63.setText("Relieve Date:");
        jLabel63.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlUpdate2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jtxtReldateUpd2.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate2.add(jtxtReldateUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("Total Allowance:       ");
        jLabel64.setPreferredSize(new java.awt.Dimension(215, 14));
        pnlUpdate2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, -1));

        jtxtAllowanceUpd2.setPreferredSize(new java.awt.Dimension(170, 19));
        pnlUpdate2.add(jtxtAllowanceUpd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jbtnUp2.setText("Update");
        jbtnUp2.setOpaque(false);
        jbtnUp2.setPreferredSize(new java.awt.Dimension(100, 30));
        pnlUpdate2.add(jbtnUp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUpdate2, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        TblPaneFeature.addTab("Update", jPanel2);

        jpnlHistory1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History Transfer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlHistory1.setPreferredSize(new java.awt.Dimension(790, 230));

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblHistory);

        javax.swing.GroupLayout jpnlHistory1Layout = new javax.swing.GroupLayout(jpnlHistory1);
        jpnlHistory1.setLayout(jpnlHistory1Layout);
        jpnlHistory1Layout.setHorizontalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlHistory1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlHistory1Layout.setVerticalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jpnlMessage1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Last Request", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlMessage1.setPreferredSize(new java.awt.Dimension(790, 250));

        tblLastReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLastReq.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblLastReq);

        javax.swing.GroupLayout jpnlMessage1Layout = new javax.swing.GroupLayout(jpnlMessage1);
        jpnlMessage1.setLayout(jpnlMessage1Layout);
        jpnlMessage1Layout.setHorizontalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMessage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlMessage1Layout.setVerticalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jLabel1.setText("Username:");

        cbbUserName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbUserNameActionPerformed(evt);
            }
        });
        cbbUserName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbUserNamePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnlHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnlMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(541, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 45, Short.MAX_VALUE)
                    .addComponent(jpnlHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(jpnlMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        TblPaneFeature.addTab("View transfer", jPanel4);

        lstTransReq.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTransReq.setPreferredSize(new java.awt.Dimension(60, 80));
        lstTransReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTransReqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTransReq);

        txtcontent.setColumns(20);
        txtcontent.setRows(5);
        jScrollPane4.setViewportView(txtcontent);

        btnAppr.setText("Approve");
        btnAppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprActionPerformed(evt);
            }
        });

        btnDeni.setText("Deni");

        jButton4.setText("Cancel");

        jLabel5.setText("List ID");

        jLabel6.setText("Content");

        jLabel7.setText("Transfer request list");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnAppr)
                        .addGap(48, 48, 48)
                        .addComponent(btnDeni, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5)
                                .addGap(307, 307, 307)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppr)
                    .addComponent(btnDeni)
                    .addComponent(jButton4))
                .addGap(32, 32, 32))
        );

        TblPaneFeature.addTab("Transfer Manager", jPanel3);

        getContentPane().add(TblPaneFeature);
    }// </editor-fold>//GEN-END:initComponents

    private void TblPaneFeatureStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TblPaneFeatureStateChanged
        // TODO add your handling code here:
        setTable(emp);
        setUser(emp);
        try {
            setlistReq();
           
        } catch (SQLException ex) {
            Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
private void setlistReq() throws SQLException{

tmo=tm.getAllTransferBy("%pending%",6);
List<String> lst= new ArrayList<String>();
DefaultListModel dlm= new DefaultListModel();
for(int i=0;i<tmo.getRowCount();i++){
dlm.addElement(tmo.getElementAt(i).getRecordID());
}

lstTransReq.setModel(dlm);
}



    private void setUser(Employee epl) {
        tf_name.setText(epl.getEmployeeName());
        jtf_EmployeeID.setText(epl.getEmployeeID() + "");
        Vector v = null;
                String loca = epl.getLocation();
                v = new Vector();
                v.add(loca);
        jcb_FrLoc.setModel(new DefaultComboBoxModel(v));
        jcb_FrLoc.setEnabled(false);
            v = null;
                String depart = epl.getCurrentDepartment();
                v = new Vector();
                v.add(depart);
      
        jcb_FrmDep.setModel(new DefaultComboBoxModel(v));
        jcb_FrmDep.setEnabled(false);
               v = null;
                String project = epl.getCurrentProject();
                v = new Vector();
                v.add(project);
        jcb_FrPro.setModel(new DefaultComboBoxModel(v));
        jcb_FrPro.setEnabled(false);

        jDc_Join.setDate(epl.getJoiningDate());
        jcb_Toloc.setModel(lm.get_AllLocation());
        jcb_Toloc.setSelectedIndex(0);
        jcb_ToDep.setModel(dcbc.get_AllDep());
        jcb_ToDep.setSelectedIndex(0);
        jcb_ToPro.setModel(pcbc.get_AllProject());
        jcb_ToPro.setSelectedIndex(0);
      
Date todayD=new Date(System.currentTimeMillis());
SimpleDateFormat dayFormat= new SimpleDateFormat("dd-MM-yyyy");
String todayS=dayFormat.format(todayD.getTime());
tf_CreateDate.setText(todayS);
    }//GEN-LAST:event_TblPaneFeatureStateChanged

    private void cbbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbUserNameActionPerformed
        // TODO add your handling code here:
   emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);

    }//GEN-LAST:event_cbbUserNameActionPerformed

    private void cbbUserNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbUserNamePropertyChange
        // TODO add your handling code here:
       emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);
    }//GEN-LAST:event_cbbUserNamePropertyChange

    private void jcb_TolocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_TolocActionPerformed
        // TODO add your handling code here:
if(rm.get_PostAllowanceByName(emp.getRole())>=0){
    float allow=lm.get_LocationAllowanceByName(jcb_Toloc.getSelectedItem().toString())+rm.get_PostAllowanceByName(emp.getRole());
        jtf_Allowance.setText(String.valueOf(allow));
        }
    }//GEN-LAST:event_jcb_TolocActionPerformed

    private void lstTransReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTransReqMouseClicked
        // TODO add your handling code here:
         int index = lstTransReq.getSelectedIndex();
        if(index > -1){
            txtcontent.setText(((TransferRecord) tmo.getElementAt(index)).toString());

        }
    }//GEN-LAST:event_lstTransReqMouseClicked

    private void btnApprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprActionPerformed
        // TODO add your handling code here:
       tm.UpdateTransferByID(Integer.parseInt(lstTransReq.getSelectedValue().toString()),"approved");
    }//GEN-LAST:event_btnApprActionPerformed
public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());} catch (Exception ex) {}

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame jf = new RequestTransfer();
                jf.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                jf.setSize(800, 600);
//                JPanel jp = new RequestTransfer();
//                jf.add(jp);
                jf.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TblPaneFeature;
    private javax.swing.JButton btnAppr;
    private javax.swing.JButton btnDeni;
    private javax.swing.JComboBox cbbUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDc_Join;
    private com.toedter.calendar.JDateChooser jDc_Rel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnUp1;
    private javax.swing.JButton jbtnUp2;
    private javax.swing.JComboBox jcb_FrLoc;
    private javax.swing.JComboBox jcb_FrPro;
    private javax.swing.JComboBox jcb_FrmDep;
    private javax.swing.JComboBox jcb_ToDep;
    private javax.swing.JComboBox jcb_ToPro;
    private javax.swing.JComboBox jcb_Toloc;
    private javax.swing.JComboBox jcmbFdepUpd2;
    private javax.swing.JComboBox jcmbFlocUpd2;
    private javax.swing.JComboBox jcmbFproUpd2;
    private javax.swing.JComboBox jcmbTodepUpd2;
    private javax.swing.JComboBox jcmbTolocUpd2;
    private javax.swing.JComboBox jcmbToproUpd2;
    private javax.swing.JPanel jpnlHistory1;
    private javax.swing.JPanel jpnlMessage1;
    private javax.swing.JTextField jtf_Allowance;
    private javax.swing.JTextField jtf_EmployeeID;
    private javax.swing.JTextField jtxtAllowanceUpd2;
    private javax.swing.JTextField jtxtCodenameUpd2;
    private javax.swing.JTextField jtxtJoindateUpd2;
    private javax.swing.JTextField jtxtNameUpd2;
    private javax.swing.JTextField jtxtReldateUpd2;
    private javax.swing.JList lstTransReq;
    private javax.swing.JPanel pnlRequest;
    private javax.swing.JPanel pnlUpdate1;
    private javax.swing.JPanel pnlUpdate2;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblLastReq;
    private javax.swing.JTextField tf_CreateDate;
    private javax.swing.JTextField tf_ReportMan;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextArea txtcontent;
    // End of variables declaration//GEN-END:variables

}
