

package GUI;
import DataAccess.DepartmentData;
import Business.DepartmentModel;
import DataAccess.LocationData;
import java.util.Vector;
import Entity.Department;
import Entity.Location;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nha.HV
 */
public class DepartmentGUI extends javax.swing.JPanel {
    LocationData locdata;
    DepartmentData deptdata;
    
    Vector<Location> locationVector;
    Vector<Department> departmentVector;

    AbstractTableModel departmentModel;
    String[] jcbbLocationModel;
    private DefaultComboBoxModel cbbmdl; 
    
    /** Creates new form DepartmentGUI */
    public DepartmentGUI() {
        initComponents();
        locdata = new LocationData();
        deptdata = new DepartmentData();
        
         afterInit();
    }
    private void afterInit(){
        departmentVector = deptdata.getAllDepartment();
        locationVector = locdata.getAllLocation();
        jcbbLocationModel = new String[locationVector.size()];
        int i =0;
        for (Location loc : locationVector) {
             jcbbLocationModel[i] = loc.getLocationAddress();
             System.out.println(loc.getLocationAddress());
            i++;
        }
        setCbbmdl(new DefaultComboBoxModel(jcbbLocationModel));
        jcbbLocation.setModel(getCbbmdl());
        
        departmentModel = new DepartmentModel(departmentVector);
        jtbDepartment.setModel(departmentModel);
        jtbDepartment.revalidate();
        DisableDeparmentInfo();
        jtfID.setText(null);
        jtfName.setText(null);
        jcbbLocation.setSelectedIndex(-1);
    }

    private void DisableDeparmentInfo() {
        jtfID.setEditable(false);
        jtfName.setEditable(false);
        jcbStatus.setEnabled(false);
        jcbbLocation.setEnabled(false);
        jbtCancel.setVisible(false);
        jbtSave.setVisible(false);
     
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDepartment = new javax.swing.JTable();
        jbtRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbID = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jlbLocation = new javax.swing.JLabel();
        jlbStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JCheckBox();
        jbtAdd = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jbtDel = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jbtSave = new javax.swing.JButton();
        jcbbLocation = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jtf_kywrd = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        jtbDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDepartment);

        jbtRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gnome-session-reboot.png"))); // NOI18N
        jbtRefresh.setText("Refresh");
        jbtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(jbtRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Infomantions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));

        jlbID.setText("ID :");

        jlbName.setText("Name: ");

        jlbLocation.setText("Location");

        jlbStatus.setText("Status");

        jcbStatus.setSelected(true);
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/opinion-agree.png"))); // NOI18N
        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jbtEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/story-editor.png"))); // NOI18N
        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/opinion-disagree.png"))); // NOI18N
        jbtDel.setText("Delete");
        jbtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDelActionPerformed(evt);
            }
        });

        jbtCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_16/dialog-error.png"))); // NOI18N
        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_16/document-save.png"))); // NOI18N
        jbtSave.setText("Save");
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });

        jcbbLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbLocation.setKeySelectionManager(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtDel)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbID)
                    .addComponent(jlbName)
                    .addComponent(jlbLocation)
                    .addComponent(jlbStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbbLocation, 0, 224, Short.MAX_VALUE)
                            .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(jtfID, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtCancel)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbStatus)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbID)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLocation)
                    .addComponent(jcbbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStatus)
                    .addComponent(jcbStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtCancel)
                    .addComponent(jbtSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDel)
                    .addComponent(jbtAdd)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 150));

        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/system-search.png"))); // NOI18N
        jbtSearch.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_kywrd, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jbtSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jtf_kywrd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSearch))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
       JDialog d = new AddADepartment(null, true);
       d.setVisible(true);
        afterInit();
        
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
    if(jtbDepartment.getSelectedRow() >= 0){
        jtfName.setEditable(true);
        jcbStatus.setEnabled(true);
        jcbbLocation.setEnabled(true);
        jbtCancel.setVisible(true);
        jbtSave.setVisible(true);
    }else{
        JOptionPane.showMessageDialog(this, "You must choose a Department to edit!");
        return;
    }
}//GEN-LAST:event_jbtEditActionPerformed
  
    private void jbtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelActionPerformed

        if(!jtfID.getText().equals(""))
        {
            int iRow  = jtbDepartment.convertRowIndexToModel(jtbDepartment.getSelectedRow()) ;
                if (iRow >= 0) {
                String Confrm = "Do you want delete selected department: " + departmentVector.get(iRow).getDepartmentName() + " ?";
                if(JOptionPane.showConfirmDialog(this, Confrm, "Confirm Delete?", JOptionPane.YES_NO_OPTION)==0){
                    int delID = Integer.valueOf(jtfID.getText());
                    try {
                        boolean isDeleted = deptdata.deleteADepartment(delID);
                        if(isDeleted){
                            RowSorter<? extends TableModel> rowSorter = jtbDepartment.getRowSorter();
                            rowSorter.rowsDeleted(iRow, iRow);
                            jtbDepartment.setModel(rowSorter.getModel());
                            jtbDepartment.revalidate();
                        }
                        else
                        {
                            deptdata.UpdateAfterDelete_Department(delID);
                            RowSorter<? extends TableModel> rowSorter = jtbDepartment.getRowSorter();
                            
                            afterInit();
                            jtbDepartment.setModel(rowSorter.getModel());
                            jtbDepartment.revalidate();
                        }
                    } catch (Exception e) {
                    }
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You must choose a department", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jbtDelActionPerformed


    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        DisableDeparmentInfo();
}//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
    if(jtfName.getText().isEmpty() || jcbbLocation.getSelectedIndex() == -1){
        
        JOptionPane.showMessageDialog(this, "The Department Name and Loacation can not empty!","Warning",JOptionPane.OK_OPTION);
        return;
    }else{
      
        Department dept = new Department();
        dept.setDepartmentID(Integer.parseInt(jtfID.getText()));
        dept.setDepartmentName(jtfName.getText());
        dept.setLocationAddress(jcbbLocation.getSelectedItem().toString());
        dept.setBooleanStatus(jcbStatus.isSelected());
        
        boolean isUpdate = deptdata.updateADepartment(dept);
        if(isUpdate){
            JOptionPane.showMessageDialog(this, "Update Sucssesfully!");
            afterInit();
        }else{
            JOptionPane.showMessageDialog(this, "Update unsuccessfully");
        }
    }   
}//GEN-LAST:event_jbtSaveActionPerformed

    private void jbtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRefreshActionPerformed
     afterInit();
}//GEN-LAST:event_jbtRefreshActionPerformed

    private void jtbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDepartmentMouseClicked
        if(jtbDepartment.getSelectedRow() >= 0){
          int index = jtbDepartment.convertRowIndexToModel(jtbDepartment.getSelectedRow());
          jtfID.setText(""+ departmentVector.get(index).getDepartmentID());
          jtfName.setText(departmentVector.get(index).getDepartmentName());
          jcbbLocation.setSelectedItem(departmentVector.get(index).getLocationAddress());
          jcbStatus.setSelected(departmentVector.get(index).getBooleanStatus());        
        }
        
    }//GEN-LAST:event_jtbDepartmentMouseClicked

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStatusActionPerformed

    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());} catch (Exception ex) {}

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                javax.swing.JFrame jf = new javax.swing.JFrame();
                jf.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                jf.setSize(800, 600);
                javax.swing.JPanel jp = new DepartmentGUI();
                jf.add(jp);
                jf.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtDel;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtRefresh;
    private javax.swing.JButton jbtSave;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JCheckBox jcbStatus;
    private javax.swing.JComboBox jcbbLocation;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbLocation;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JTable jtbDepartment;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtf_kywrd;
    // End of variables declaration//GEN-END:variables
    public DefaultComboBoxModel getComboBoxModel(){
        return this.getCbbmdl();
    }

    /**
     * @return the cbbmdl
     */
    public DefaultComboBoxModel getCbbmdl() {
        return cbbmdl;
    }

    /**
     * @param cbbmdl the cbbmdl to set
     */
    public void setCbbmdl(DefaultComboBoxModel cbbmdl) {
        this.cbbmdl = cbbmdl;
    }
    
    
}
