/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestTransfer.java
 *
 * Created on Apr 2, 2011, 11:08:24 PM
 */

package GUI;

import Business.*;
import Entity.*;
import DataAccess.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Lovely
 */
public class RequestTransfer extends javax.swing.JDialog {
private ProjectComboBoxControler pcbc = new ProjectComboBoxControler();
private DepartmentComboBoxControler dcbc = new DepartmentComboBoxControler();
private RoleComboBoxControler rcbc = new RoleComboBoxControler();
private LocationComboboxControler lcbc = new  LocationComboboxControler();
private TransferManagement tm = new TransferManagement();
private EmployeeManager em = new EmployeeManager();
private AdminData ad= new AdminData();
private TransferModel tmo = new TransferModel();
public  Employee emp = new Employee();
public  int iRecord;
private TransferRecord tr = new TransferRecord();
private DefaultComboBoxModel dcbm= new DefaultComboBoxModel();

    /** Creates new form RequestTransfer */

public RequestTransfer(java.awt.Frame parent, boolean modal,Employee epl,int irc) {
       super(parent, modal);
        initComponents();
        emp=epl;
        iRecord =irc;
        setTable(emp);
        EmployeeModel emod = em.getAllEmployee();
        DefaultComboBoxModel dcbm1 = new  DefaultComboBoxModel();
        for(int i=0;i<emod.getRowCount();i++){
        dcbm1.addElement(emod.getEmployeeAt(i).getUsername());
        }
        setUser(emp,iRecord);
        cbbUserName.setModel(dcbm1);
        String stritem="";
        dcbm.removeAllElements();
        stritem = emp.getEmployeeName();
        dcbm.addElement(stritem);
        cbbEName.setModel(dcbm);
        cbbEName.setSelectedItem(stritem);
        DefaultComboBoxModel dcbm2 = new  DefaultComboBoxModel();
        dcbm2.addElement(String.valueOf(iRecord));
        cbbRid.setModel(dcbm2);
   
    }
   
private void setTable(Employee e) {

        tblHistory.setModel(tm.getAllTransferByEmpID(e.getEmployeeID()));
        tblHistory.setFillsViewportHeight(true);
        tblHistory.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(12).setPreferredWidth(60);

        tblLastReq.setModel(tm.getLastTransferByEmpID(e.getEmployeeID()));
        tblLastReq.setFillsViewportHeight(true);
        tblLastReq.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblLastReq.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblLastReq.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblLastReq.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(12).setPreferredWidth(60);
 
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRequest = new javax.swing.JPanel();
        TblPaneFeature = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jpnlHistory1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jpnlMessage1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLastReq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbbUserName = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbbEName = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTransReq = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcontent = new javax.swing.JTextArea();
        btnAppr = new javax.swing.JButton();
        btnDeni = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlUpdate1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jtf_EmployeeID = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jtf_Allowance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDc_Join = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ReportMan = new javax.swing.JTextField();
        tf_CreateDate = new javax.swing.JTextField();
        jbtnUp3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_toloc = new javax.swing.JTextField();
        tf_todep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_topro = new javax.swing.JTextField();
        tf_frLoc = new javax.swing.JTextField();
        tf_frdep = new javax.swing.JTextField();
        tf_frpro = new javax.swing.JTextField();
        cbbRid = new javax.swing.JComboBox();

        pnlRequest.setPreferredSize(new java.awt.Dimension(790, 510));

        javax.swing.GroupLayout pnlRequestLayout = new javax.swing.GroupLayout(pnlRequest);
        pnlRequest.setLayout(pnlRequestLayout);
        pnlRequestLayout.setHorizontalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        pnlRequestLayout.setVerticalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new java.awt.FlowLayout());

        TblPaneFeature.setPreferredSize(new java.awt.Dimension(800, 600));
        TblPaneFeature.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TblPaneFeatureStateChanged(evt);
            }
        });

        jpnlHistory1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History Transfer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlHistory1.setPreferredSize(new java.awt.Dimension(790, 230));

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblHistory);

        javax.swing.GroupLayout jpnlHistory1Layout = new javax.swing.GroupLayout(jpnlHistory1);
        jpnlHistory1.setLayout(jpnlHistory1Layout);
        jpnlHistory1Layout.setHorizontalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlHistory1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlHistory1Layout.setVerticalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jpnlMessage1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Last Request", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlMessage1.setPreferredSize(new java.awt.Dimension(790, 250));

        tblLastReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLastReq.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblLastReq);

        javax.swing.GroupLayout jpnlMessage1Layout = new javax.swing.GroupLayout(jpnlMessage1);
        jpnlMessage1.setLayout(jpnlMessage1Layout);
        jpnlMessage1Layout.setHorizontalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMessage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlMessage1Layout.setVerticalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jLabel1.setText("Username:");

        cbbUserName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbUserNameActionPerformed(evt);
            }
        });
        cbbUserName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbUserNamePropertyChange(evt);
            }
        });

        jLabel11.setText("Employee Name:");

        cbbEName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbEName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnlHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpnlMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbbEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(533, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(jpnlHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(jpnlMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );

        TblPaneFeature.addTab("View transfer", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-certificate.png")), jPanel4); // NOI18N

        lstTransReq.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer list"));
        lstTransReq.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTransReq.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTransReq.setPreferredSize(new java.awt.Dimension(60, 80));
        lstTransReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTransReqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTransReq);

        txtcontent.setColumns(20);
        txtcontent.setEditable(false);
        txtcontent.setRows(5);
        txtcontent.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Transfer Information "));
        jScrollPane4.setViewportView(txtcontent);

        btnAppr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/emblem-default.png"))); // NOI18N
        btnAppr.setText("Approve");
        btnAppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprActionPerformed(evt);
            }
        });

        btnDeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/dialog-error.png"))); // NOI18N
        btnDeni.setText("Deny");
        btnDeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeniActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gnome-session-halt.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("List Transfer request");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(btnAppr)
                .addGap(18, 18, 18)
                .addComponent(btnDeni)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnAppr)
                    .addComponent(btnDeni)
                    .addComponent(jButton4))
                .addGap(72, 72, 72))
        );

        TblPaneFeature.addTab("Transfer Manager", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-pim-contacts.png")), jPanel3); // NOI18N

        pnlUpdate1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        pnlUpdate1.setPreferredSize(new java.awt.Dimension(500, 33));

        jLabel33.setText("Employee Identity:");
        jLabel33.setPreferredSize(new java.awt.Dimension(100, 14));

        jtf_EmployeeID.setEnabled(false);
        jtf_EmployeeID.setPreferredSize(new java.awt.Dimension(170, 19));

        jLabel35.setText("Employee Name:");
        jLabel35.setPreferredSize(new java.awt.Dimension(100, 14));

        tf_name.setEditable(false);
        tf_name.setPreferredSize(new java.awt.Dimension(170, 19));

        jLabel37.setText("From Department:");
        jLabel37.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel39.setText("To Department:");
        jLabel39.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel41.setText("From Location:");
        jLabel41.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel43.setText("To Location:");
        jLabel43.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel45.setText("From Project:");
        jLabel45.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel49.setText("Join Date:");
        jLabel49.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel4.setPreferredSize(new java.awt.Dimension(100, 1));

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Total Allowance:       ");
        jLabel53.setPreferredSize(new java.awt.Dimension(215, 14));

        jtf_Allowance.setEnabled(false);
        jtf_Allowance.setPreferredSize(new java.awt.Dimension(170, 19));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gnome-session-halt.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDc_Join.setEnabled(false);

        jLabel2.setText("Reporting Manager:");

        jLabel3.setText("Creation Date:");

        tf_ReportMan.setEditable(false);

        tf_CreateDate.setEditable(false);

        jbtnUp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-certificate-sign.png"))); // NOI18N
        jbtnUp3.setText("Complete");
        jbtnUp3.setOpaque(false);
        jbtnUp3.setPreferredSize(new java.awt.Dimension(100, 30));
        jbtnUp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUp3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Transfer record identity:");

        jLabel6.setText("To project:");

        cbbRid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbRid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbRidActionPerformed(evt);
            }
        });
        cbbRid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbbRidFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlUpdate1Layout = new javax.swing.GroupLayout(pnlUpdate1);
        pnlUpdate1.setLayout(pnlUpdate1Layout);
        pnlUpdate1Layout.setHorizontalGroup(
            pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdate1Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlUpdate1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jbtnUp3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdate1Layout.createSequentialGroup()
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlUpdate1Layout.createSequentialGroup()
                            .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_frpro, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_frdep, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5))
                                        .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_frLoc)
                                        .addComponent(jtf_EmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(52, 52, 52))
                        .addGroup(pnlUpdate1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jDc_Join, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_Allowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(tf_ReportMan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdate1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(tf_CreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdate1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(tf_topro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdate1Layout.createSequentialGroup()
                        .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_toloc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUpdate1Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(tf_todep, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
            .addGroup(pnlUpdate1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbRid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        pnlUpdate1Layout.setVerticalGroup(
            pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdate1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbRid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUpdate1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtf_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_frLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(tf_toloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_frdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tf_todep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_frpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tf_topro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tf_CreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdate1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDc_Join, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_Allowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_ReportMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(71, 71, 71)
                .addGroup(pnlUpdate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnUp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TblPaneFeature.addTab("Complete Transfer", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-certificate-sign.png")), jPanel2); // NOI18N

        getContentPane().add(TblPaneFeature);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-898)/2, (screenSize.height-665)/2, 898, 665);
    }// </editor-fold>//GEN-END:initComponents

    private void TblPaneFeatureStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TblPaneFeatureStateChanged
        // TODO add your handling code here:
        setTable(emp);
        setUser(emp,iRecord);
        try {
            setlistReq();

        } catch (SQLException ex) {
            Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setlistReq() throws SQLException{

        tmo=tm.getAllTransferBy("%pending%",6);
        List<String> lst= new ArrayList<String>();
        DefaultListModel dlm= new DefaultListModel();
        for(int i=0;i<tmo.getRowCount();i++){
            dlm.addElement(tmo.getElementAt(i).getRecordID());
        }
    lstTransReq.setModel(dlm);
   }



    private void setUser(Employee epl,int iRec) {
        tf_name.setText(epl.getEmployeeName());
        jtf_EmployeeID.setText(epl.getEmployeeID() + "");
        String loca = epl.getLocation();
        tf_frLoc.setText(loca);
        String depart = epl.getCurrentDepartment();
        tf_frdep.setText(depart);
        String project = epl.getCurrentProject();
        tf_frpro.setText(project);
        jDc_Join.setDate(epl.getJoiningDate());
        tr=tm.getTransferByTransferID(iRec);
        if(!(tr==null)){
        tf_toloc.setText(tr.getLocationAddress());
        tf_todep.setText(tr.getDepartmentName());
        tf_topro.setText(tr.getProjectName());
        tf_CreateDate.setText(tr.getCreationDate().toString());
        tf_ReportMan.setText(tr.getReportingManager());
        jtf_Allowance.setText(String.valueOf(tr.getAllowance()));
        }
}//GEN-LAST:event_TblPaneFeatureStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jButton4ActionPerformed

    private void btnDeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeniActionPerformed
        // TODO add your handling code here:
        String admname="";
        ResultSet rs=ad.getAdminData(Session.getLoginID());
        try {
            while (rs.next()) {
                admname = rs.getString("Adminname");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!lstTransReq.getSelectedValue().toString().isEmpty()){



            boolean bl=   tm.UpdateTransferByID(Integer.parseInt(lstTransReq.getSelectedValue().toString()),"denied",admname,0);
            if(bl){ JOptionPane.showMessageDialog(this,"Deny a transfer success!","Alert",1); txtcontent.setText("");
            } else { JOptionPane.showMessageDialog(this,"Deny a transfer not success!","Alert",1);}
            try {
                setlistReq();

            } catch (SQLException ex) {
                Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
}//GEN-LAST:event_btnDeniActionPerformed

    private void btnApprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprActionPerformed
        // TODO add your handling code here:
        String admname="";
        ResultSet rs=ad.getAdminData(Session.getLoginID());
        try {
            while (rs.next()) {
                try {
                    admname = rs.getString("Adminname");
                } catch (SQLException ex) {
                    Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!lstTransReq.getSelectedValue().toString().isEmpty()) {
            float allow = lcbc.get_LocationAllowanceByName(tr.getLocationAddress())+ rcbc.get_PostAllowanceByName(emp.getRole());
            boolean bl=  tm.UpdateTransferByID(Integer.parseInt(lstTransReq.getSelectedValue().toString()), "approved",admname,allow);
            if(bl){ JOptionPane.showMessageDialog(this,"Approve new employee transfer success!","Message",1);txtcontent.setText(""); } else { JOptionPane.showMessageDialog(this,"Approve new employee transfer not success!","Message",1);}

            try {
                setlistReq();
            } catch (SQLException ex) {
                Logger.getLogger(RequestTransfer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btnApprActionPerformed

    private void lstTransReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTransReqMouseClicked
        // TODO add your handling code here:
        int index = lstTransReq.getSelectedIndex();
        if(index > -1){
            txtcontent.setText(((TransferRecord) tmo.getElementAt(index)).toString());
             tr=(TransferRecord) tmo.getElementAt(index);
             emp=em.getAllEmployeeByID(tr.getEmployeeID());
        }
}//GEN-LAST:event_lstTransReqMouseClicked

    private void cbbUserNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbUserNamePropertyChange
        // TODO add your handling code here:
        emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);
}//GEN-LAST:event_cbbUserNamePropertyChange

    private void cbbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbUserNameActionPerformed
        // TODO add your handling code here:
        emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);
        String stritem="";
        dcbm.removeAllElements();
        stritem = emp.getEmployeeName();
        dcbm.addElement(stritem);
        cbbEName.setModel(dcbm);
        cbbEName.setSelectedIndex(0);
        cbbEName.setSelectedItem(stritem);
}//GEN-LAST:event_cbbUserNameActionPerformed

    private void jbtnUp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUp3ActionPerformed
        // TODO add your handling code here:
  emp=em.getAllEmployeeByID(tr.getEmployeeID());
  boolean bl = em.updateEWorkitem(emp, tr.getWorkItemID());
  if(bl){ JOptionPane.showMessageDialog(this,"Complete transfer success!","Alert",1);
            } else { JOptionPane.showMessageDialog(this,"Complete a transfer not success!","Alert",1);}
    }//GEN-LAST:event_jbtnUp3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbRidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbRidActionPerformed
        // TODO add your handling code here:
        tr=tm.getTransferByTransferID(Integer.parseInt(cbbRid.getSelectedItem().toString()));
        emp=em.getAllEmployeeByID(tr.getEmployeeID());
        setUser(emp,Integer.parseInt(cbbRid.getSelectedItem().toString()));
    }//GEN-LAST:event_cbbRidActionPerformed

    private void cbbRidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbRidFocusGained
        // TODO add your handling code here:
        DefaultComboBoxModel dcbm3 = new  DefaultComboBoxModel();
        dcbm3=tm.getAllTransferID();
        cbbRid.setModel(dcbm3);
    }//GEN-LAST:event_cbbRidFocusGained
public static void main(String args[]) {
//        try {
//            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());} catch (Exception ex) {}
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//               RequestTransfer jf = new RequestTransfer(new javax.swing.JFrame(), true);
//                jf.setDefaultCloseOperation(javax.swing.WindowConstants. HIDE_ON_CLOSE);
//
//
//       jf.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                jf.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TblPaneFeature;
    private javax.swing.JButton btnAppr;
    private javax.swing.JButton btnDeni;
    private javax.swing.JComboBox cbbEName;
    private javax.swing.JComboBox cbbRid;
    private javax.swing.JComboBox cbbUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDc_Join;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnUp3;
    private javax.swing.JPanel jpnlHistory1;
    private javax.swing.JPanel jpnlMessage1;
    private javax.swing.JTextField jtf_Allowance;
    private javax.swing.JTextField jtf_EmployeeID;
    private javax.swing.JList lstTransReq;
    private javax.swing.JPanel pnlRequest;
    private javax.swing.JPanel pnlUpdate1;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblLastReq;
    private javax.swing.JTextField tf_CreateDate;
    private javax.swing.JTextField tf_ReportMan;
    private javax.swing.JTextField tf_frLoc;
    private javax.swing.JTextField tf_frdep;
    private javax.swing.JTextField tf_frpro;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_todep;
    private javax.swing.JTextField tf_toloc;
    private javax.swing.JTextField tf_topro;
    private javax.swing.JTextArea txtcontent;
    // End of variables declaration//GEN-END:variables

}
