/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestTransfer.java
 *
 * Created on Apr 2, 2011, 11:08:24 PM
 */

package GUI;

import Business.*;
import Entity.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;

/**
 *
 * @author Lovely
 */
public class Employee_viewtransfer extends javax.swing.JPanel {

private TransferManagement tm = new TransferManagement();
private EmployeeManager em = new EmployeeManager();

public  Employee emp = new Employee();
public  int iRecord;
private TransferRecord tr = new TransferRecord();
private DefaultComboBoxModel dcbm= new DefaultComboBoxModel();

    /** Creates new form RequestTransfer */
 Employee_ProfileManagement employee_ProMan = null;


public Employee_viewtransfer() {
        initComponents();
        employee_ProMan = new Employee_ProfileManagement();
        emp = new Employee();
        emp = employee_ProMan.getEmployeeProfile(Session.getLoginID());
        setTable(emp);
        DefaultComboBoxModel dcbm1 = new  DefaultComboBoxModel();
        dcbm1.addElement(emp.getUsername());
        cbbUserName.setModel(dcbm1);
        String stritem="";
        dcbm.removeAllElements();
        stritem = emp.getEmployeeName();
        dcbm.addElement(stritem);
        cbbEName.setModel(dcbm);
        cbbEName.setSelectedItem(stritem);
       
   
    }
   
private void setTable(Employee e) {

        tblHistory.setModel(tm.getAllTransferByEmpID(e.getEmployeeID()));
        tblHistory.setFillsViewportHeight(true);
        tblHistory.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblHistory.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblHistory.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblHistory.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblHistory.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblHistory.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(12).setPreferredWidth(60);

        tblLastReq.setModel(tm.getLastTransferByEmpID(e.getEmployeeID()));
        tblLastReq.setFillsViewportHeight(true);
        tblLastReq.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblLastReq.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblLastReq.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblLastReq.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(8).setPreferredWidth(160);
        tblLastReq.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblLastReq.getColumnModel().getColumn(10).setPreferredWidth(100);
        tblLastReq.getColumnModel().getColumn(11).setPreferredWidth(100);
        tblHistory.getColumnModel().getColumn(12).setPreferredWidth(60);
 
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jpnlHistory1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jpnlMessage1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLastReq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbbUserName = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbbEName = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jpnlHistory1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History Transfer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlHistory1.setPreferredSize(new java.awt.Dimension(790, 230));

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblHistory);

        javax.swing.GroupLayout jpnlHistory1Layout = new javax.swing.GroupLayout(jpnlHistory1);
        jpnlHistory1.setLayout(jpnlHistory1Layout);
        jpnlHistory1Layout.setHorizontalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlHistory1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlHistory1Layout.setVerticalGroup(
            jpnlHistory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlHistory1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnlMessage1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Last Request", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlMessage1.setPreferredSize(new java.awt.Dimension(790, 250));

        tblLastReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLastReq.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblLastReq);

        javax.swing.GroupLayout jpnlMessage1Layout = new javax.swing.GroupLayout(jpnlMessage1);
        jpnlMessage1.setLayout(jpnlMessage1Layout);
        jpnlMessage1Layout.setHorizontalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMessage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlMessage1Layout.setVerticalGroup(
            jpnlMessage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        jLabel1.setText("Username:");

        cbbUserName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbUserNameActionPerformed(evt);
            }
        });
        cbbUserName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbUserNamePropertyChange(evt);
            }
        });

        jLabel11.setText("Employee Name:");

        cbbEName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbEName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(693, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpnlMessage1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                        .addComponent(jpnlHistory1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                    .addGap(0, 0, 0)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbbEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jpnlHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnlMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbUserNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbUserNamePropertyChange
        // TODO add your handling code here:
        emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);
}//GEN-LAST:event_cbbUserNamePropertyChange

    private void cbbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbUserNameActionPerformed
        // TODO add your handling code here:
        emp=em.getEmployeeByUsername(cbbUserName.getSelectedItem().toString());
        setTable(emp);
        String stritem="";
        dcbm.removeAllElements();
        stritem = emp.getEmployeeName();
        dcbm.addElement(stritem);
        cbbEName.setModel(dcbm);
        cbbEName.setSelectedIndex(0);
        cbbEName.setSelectedItem(stritem);
}//GEN-LAST:event_cbbUserNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setTable(emp);
    }//GEN-LAST:event_jButton1ActionPerformed
public static void main(String args[]) {
//        try {
//            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());} catch (Exception ex) {}
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//               RequestTransfer jf = new RequestTransfer(new javax.swing.JFrame(), true);
//                jf.setDefaultCloseOperation(javax.swing.WindowConstants. HIDE_ON_CLOSE);
//
//
//       jf.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                jf.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbEName;
    private javax.swing.JComboBox cbbUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpnlHistory1;
    private javax.swing.JPanel jpnlMessage1;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblLastReq;
    // End of variables declaration//GEN-END:variables

}
