/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrameGUI.java
 *
 * Created on 14-03-2011, 16:41:18
 */

package GUI;

import DataAccess.StatiticsData;
import Entity.Session;
import java.awt.GraphicsEnvironment;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author nhahv
 */
public class MainFrameGUI extends javax.swing.JFrame {
//    private String vi_VN = lang.getString("VI_VN");
StatiticsData statData;
int[] sta;
    private JFrame mainFrame;
    /** Creates new form MainFrameGUI */
    public MainFrameGUI() {
         statData = new StatiticsData();
                      initComponents();
       
       
        dspPerSes();
    }

    MainFrameGUI(boolean type, String username, int emp) {
       if(type == true){
           this.UserName = username;
       }else{
           this.empID = emp;
           
       }
       }

    private void exiting() throws HeadlessException {
        int e = JOptionPane.showConfirmDialog(this, "Do you want exit now?", "Exit now?", JOptionPane.OK_CANCEL_OPTION);
        System.out.println(e);
        if (e == 0) {
            System.exit(e);
        }
    }

    private void logout() throws HeadlessException {
        int e = JOptionPane.showConfirmDialog(this, "Do you want exit now?", "Exit now?", JOptionPane.OK_CANCEL_OPTION);
        System.out.println(e);
        if (e == 0) {
            this.dispose();
            Session session = new Session();
            new LoginGUI().setVisible(true);
        }
    }
      
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glossPainter1 = new org.jdesktop.swingx.painter.GlossPainter();
        menuRadioGroup = new javax.swing.ButtonGroup();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Profile = new javax.swing.JPanel();
        PANEL_PROFILE = new javax.swing.JPanel();
        jXHeader3 = new org.jdesktop.swingx.JXHeader();
        jPanel_Transfer = new javax.swing.JPanel();
        PANEL_TRANSFER = new javax.swing.JPanel();
        jXHeader6 = new org.jdesktop.swingx.JXHeader();
        jPanel_workItem = new javax.swing.JPanel();
        PANEL_WORKITEM = new javax.swing.JPanel();
        jXHeader8 = new org.jdesktop.swingx.JXHeader();
        jPanel_Employee = new javax.swing.JPanel();
        PANEL_EMPLOYEE = new javax.swing.JPanel();
        jXHeader2 = new org.jdesktop.swingx.JXHeader();
        jPanel_Role = new javax.swing.JPanel();
        PANEL_ROLE = new javax.swing.JPanel();
        jXHeader7 = new org.jdesktop.swingx.JXHeader();
        jPanel_Project = new javax.swing.JPanel();
        PANEL_PROJECT = new javax.swing.JPanel();
        jXHeader4 = new org.jdesktop.swingx.JXHeader();
        jPanel_Department = new javax.swing.JPanel();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        PANEL_DEPATMENT = new javax.swing.JPanel();
        jPanel_Location = new javax.swing.JPanel();
        PANEL_LOCATION = new javax.swing.JPanel();
        jXHeader5 = new org.jdesktop.swingx.JXHeader();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_System = new javax.swing.JMenu();
        jMenu_Logout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jAbout = new javax.swing.JCheckBoxMenuItem();

        jMenuItem6.setText("jMenuItem6");
        jMenuItem6.setName("jMenuItem6"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee Transfer Manager 1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setAutoscrolls(true);
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jTabbedPane1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);
        jTabbedPane1.setName("jTP_Profile"); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTabbedPane1HierarchyChanged(evt);
            }
        });

        jPanel_Profile.setName("jPanel_Profile"); // NOI18N

        PANEL_PROFILE.setName("PANEL_PROFILE"); // NOI18N

        javax.swing.GroupLayout PANEL_PROFILELayout = new javax.swing.GroupLayout(PANEL_PROFILE);
        PANEL_PROFILE.setLayout(PANEL_PROFILELayout);
        PANEL_PROFILELayout.setHorizontalGroup(
            PANEL_PROFILELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1072, Short.MAX_VALUE)
        );
        PANEL_PROFILELayout.setVerticalGroup(
            PANEL_PROFILELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jXHeader3.setBackground(new java.awt.Color(204, 0, 51));
        jXHeader3.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader3.setBackgroundPainter(glossPainter1);
        jXHeader3.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader3.setName("jXHeader3"); // NOI18N
        jXHeader3.setPreferredSize(new java.awt.Dimension(163, 50));
        jXHeader3.setTitle("Profile");
        jXHeader3.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_PROFILE = new ProfileManagementGUI();

        javax.swing.GroupLayout jPanel_ProfileLayout = new javax.swing.GroupLayout(jPanel_Profile);
        jPanel_Profile.setLayout(jPanel_ProfileLayout);
        jPanel_ProfileLayout.setHorizontalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addComponent(PANEL_PROFILE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ProfileLayout.setVerticalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addComponent(jXHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_PROFILE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   Profile     ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-process-own.png")), jPanel_Profile); // NOI18N

        jPanel_Transfer.setName("jPanel_Transfer"); // NOI18N

        PANEL_TRANSFER.setName("PANEL_TRANSFER"); // NOI18N

        javax.swing.GroupLayout PANEL_TRANSFERLayout = new javax.swing.GroupLayout(PANEL_TRANSFER);
        PANEL_TRANSFER.setLayout(PANEL_TRANSFERLayout);
        PANEL_TRANSFERLayout.setHorizontalGroup(
            PANEL_TRANSFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        PANEL_TRANSFERLayout.setVerticalGroup(
            PANEL_TRANSFERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader6.setBackground(new java.awt.Color(255, 102, 102));
        jXHeader6.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader6.setBackgroundPainter(glossPainter1);
        jXHeader6.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader6.setName("jXHeader6"); // NOI18N
        jXHeader6.setPreferredSize(new java.awt.Dimension(444, 50));
        jXHeader6.setTitle("Transfer Management");
        jXHeader6.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_TRANSFER = new TransferGUI();

        javax.swing.GroupLayout jPanel_TransferLayout = new javax.swing.GroupLayout(jPanel_Transfer);
        jPanel_Transfer.setLayout(jPanel_TransferLayout);
        jPanel_TransferLayout.setHorizontalGroup(
            jPanel_TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_TransferLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_TRANSFER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel_TransferLayout.setVerticalGroup(
            jPanel_TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TransferLayout.createSequentialGroup()
                .addComponent(jXHeader6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_TRANSFER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Transfer    ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/checking.png")), jPanel_Transfer); // NOI18N

        jPanel_workItem.setName("jPanel_workItem"); // NOI18N

        PANEL_WORKITEM.setName("PANEL_WORKITEM"); // NOI18N

        javax.swing.GroupLayout PANEL_WORKITEMLayout = new javax.swing.GroupLayout(PANEL_WORKITEM);
        PANEL_WORKITEM.setLayout(PANEL_WORKITEMLayout);
        PANEL_WORKITEMLayout.setHorizontalGroup(
            PANEL_WORKITEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        PANEL_WORKITEMLayout.setVerticalGroup(
            PANEL_WORKITEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader8.setBackground(new java.awt.Color(102, 0, 102));
        jXHeader8.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader8.setBackgroundPainter(glossPainter1);
        jXHeader8.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader8.setName("jXHeader8"); // NOI18N
        jXHeader8.setPreferredSize(new java.awt.Dimension(446, 50));
        jXHeader8.setTitle("Work items Management");
        jXHeader8.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_WORKITEM = new WorkItemGUI();

        javax.swing.GroupLayout jPanel_workItemLayout = new javax.swing.GroupLayout(jPanel_workItem);
        jPanel_workItem.setLayout(jPanel_workItemLayout);
        jPanel_workItemLayout.setHorizontalGroup(
            jPanel_workItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_workItemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_WORKITEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_workItemLayout.setVerticalGroup(
            jPanel_workItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_workItemLayout.createSequentialGroup()
                .addComponent(jXHeader8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_WORKITEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   Work Items   ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-calendar-month.png")), jPanel_workItem); // NOI18N

        jPanel_Employee.setAlignmentX(0.0F);
        jPanel_Employee.setAlignmentY(0.0F);
        jPanel_Employee.setName("jPanel_Employee"); // NOI18N

        PANEL_EMPLOYEE.setName("PANEL_EMPLOYEE"); // NOI18N

        javax.swing.GroupLayout PANEL_EMPLOYEELayout = new javax.swing.GroupLayout(PANEL_EMPLOYEE);
        PANEL_EMPLOYEE.setLayout(PANEL_EMPLOYEELayout);
        PANEL_EMPLOYEELayout.setHorizontalGroup(
            PANEL_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        PANEL_EMPLOYEELayout.setVerticalGroup(
            PANEL_EMPLOYEELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader2.setBackground(new java.awt.Color(153, 0, 204));
        jXHeader2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader2.setBackgroundPainter(glossPainter1);
        jXHeader2.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader2.setName("jXHeader2"); // NOI18N
        jXHeader2.setPreferredSize(new java.awt.Dimension(466, 50));
        jXHeader2.setTitle("Employee Management");
        jXHeader2.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_EMPLOYEE = new EmployeeGUI();

        javax.swing.GroupLayout jPanel_EmployeeLayout = new javax.swing.GroupLayout(jPanel_Employee);
        jPanel_Employee.setLayout(jPanel_EmployeeLayout);
        jPanel_EmployeeLayout.setHorizontalGroup(
            jPanel_EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_EmployeeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_EMPLOYEE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_EmployeeLayout.setVerticalGroup(
            jPanel_EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EmployeeLayout.createSequentialGroup()
                .addComponent(jXHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_EMPLOYEE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   Employee    ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/meeting-organizer.png")), jPanel_Employee); // NOI18N

        jPanel_Role.setName("jPanel_Role"); // NOI18N

        PANEL_ROLE.setName("PANEL_ROLE"); // NOI18N

        javax.swing.GroupLayout PANEL_ROLELayout = new javax.swing.GroupLayout(PANEL_ROLE);
        PANEL_ROLE.setLayout(PANEL_ROLELayout);
        PANEL_ROLELayout.setHorizontalGroup(
            PANEL_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        PANEL_ROLELayout.setVerticalGroup(
            PANEL_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader7.setBackground(new java.awt.Color(0, 102, 102));
        jXHeader7.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader7.setBackgroundPainter(glossPainter1);
        jXHeader7.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader7.setName("jXHeader7"); // NOI18N
        jXHeader7.setPreferredSize(new java.awt.Dimension(446, 50));
        jXHeader7.setScrollableTracksViewportWidth(false);
        jXHeader7.setTitle("Role Management");
        jXHeader7.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_ROLE = new PostGUI();

        javax.swing.GroupLayout jPanel_RoleLayout = new javax.swing.GroupLayout(jPanel_Role);
        jPanel_Role.setLayout(jPanel_RoleLayout);
        jPanel_RoleLayout.setHorizontalGroup(
            jPanel_RoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_RoleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_ROLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_RoleLayout.setVerticalGroup(
            jPanel_RoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RoleLayout.createSequentialGroup()
                .addComponent(jXHeader7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_ROLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("       Role       ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/resource-calendar-child.png")), jPanel_Role); // NOI18N

        jPanel_Project.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_Project.setName("jPanel_Project"); // NOI18N

        PANEL_PROJECT.setName("PANEL_PROJECT"); // NOI18N

        javax.swing.GroupLayout PANEL_PROJECTLayout = new javax.swing.GroupLayout(PANEL_PROJECT);
        PANEL_PROJECT.setLayout(PANEL_PROJECTLayout);
        PANEL_PROJECTLayout.setHorizontalGroup(
            PANEL_PROJECTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        PANEL_PROJECTLayout.setVerticalGroup(
            PANEL_PROJECTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader4.setBackground(new java.awt.Color(0, 153, 51));
        jXHeader4.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader4.setBackgroundPainter(glossPainter1);
        jXHeader4.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader4.setName("jXHeader4"); // NOI18N
        jXHeader4.setPreferredSize(new java.awt.Dimension(421, 50));
        jXHeader4.setTitle("Project Management");
        jXHeader4.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_PROJECT = new ProjectManagementGUI();

        javax.swing.GroupLayout jPanel_ProjectLayout = new javax.swing.GroupLayout(jPanel_Project);
        jPanel_Project.setLayout(jPanel_ProjectLayout);
        jPanel_ProjectLayout.setHorizontalGroup(
            jPanel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_ProjectLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_PROJECT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_ProjectLayout.setVerticalGroup(
            jPanel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProjectLayout.createSequentialGroup()
                .addComponent(jXHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_PROJECT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("      Project      ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/view-calendar-time-spent.png")), jPanel_Project); // NOI18N

        jPanel_Department.setName("jPanel_Department"); // NOI18N

        jXHeader1.setBackground(new java.awt.Color(0, 153, 204));
        jXHeader1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader1.setBackgroundPainter(glossPainter1);
        jXHeader1.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader1.setName("jXHeader1"); // NOI18N
        jXHeader1.setPreferredSize(new java.awt.Dimension(431, 50));
        jXHeader1.setTitle("Department Manager");
        jXHeader1.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_DEPATMENT.setName("PANEL_DEPATMENT"); // NOI18N

        javax.swing.GroupLayout PANEL_DEPATMENTLayout = new javax.swing.GroupLayout(PANEL_DEPATMENT);
        PANEL_DEPATMENT.setLayout(PANEL_DEPATMENTLayout);
        PANEL_DEPATMENTLayout.setHorizontalGroup(
            PANEL_DEPATMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        PANEL_DEPATMENTLayout.setVerticalGroup(
            PANEL_DEPATMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        PANEL_DEPATMENT = new DepartmentGUI();

        javax.swing.GroupLayout jPanel_DepartmentLayout = new javax.swing.GroupLayout(jPanel_Department);
        jPanel_Department.setLayout(jPanel_DepartmentLayout);
        jPanel_DepartmentLayout.setHorizontalGroup(
            jPanel_DepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_DepartmentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_DEPATMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel_DepartmentLayout.setVerticalGroup(
            jPanel_DepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DepartmentLayout.createSequentialGroup()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_DEPATMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Department    ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/internet-telephony.png")), jPanel_Department); // NOI18N

        jPanel_Location.setName("jPanel_Location"); // NOI18N

        PANEL_LOCATION.setName("PANEL_LOCATION"); // NOI18N

        javax.swing.GroupLayout PANEL_LOCATIONLayout = new javax.swing.GroupLayout(PANEL_LOCATION);
        PANEL_LOCATION.setLayout(PANEL_LOCATIONLayout);
        PANEL_LOCATIONLayout.setHorizontalGroup(
            PANEL_LOCATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        PANEL_LOCATIONLayout.setVerticalGroup(
            PANEL_LOCATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jXHeader5.setBackground(new java.awt.Color(102, 102, 0));
        jXHeader5.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jXHeader5.setBackgroundPainter(glossPainter1);
        jXHeader5.setFont(new java.awt.Font("Tahoma", 3, 36));
        jXHeader5.setName("jXHeader5"); // NOI18N
        jXHeader5.setPreferredSize(new java.awt.Dimension(446, 50));
        jXHeader5.setTitle("Location Management");
        jXHeader5.setTitleForeground(new java.awt.Color(255, 255, 255));

        PANEL_LOCATION = new LocationGUI();

        javax.swing.GroupLayout jPanel_LocationLayout = new javax.swing.GroupLayout(jPanel_Location);
        jPanel_Location.setLayout(jPanel_LocationLayout);
        jPanel_LocationLayout.setHorizontalGroup(
            jPanel_LocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel_LocationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PANEL_LOCATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel_LocationLayout.setVerticalGroup(
            jPanel_LocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LocationLayout.createSequentialGroup()
                .addComponent(jXHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_LOCATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("    Location      ", new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/preferences-desktop-locale.png")), jPanel_Location); // NOI18N

        jLabel1.setText("Emplyee Transfer Managerment System™  version 1.0");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Registered ® 2011 by Group One");
        jLabel2.setName("jLabel2"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 659, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu_System.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/go-home.png"))); // NOI18N
        jMenu_System.setText("     System      ");
        jMenu_System.setName("jMenu_System"); // NOI18N

        jMenu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gnome-session-halt.png"))); // NOI18N
        jMenu_Logout.setText("Log out");
        jMenu_Logout.setName("jMenu_Logout"); // NOI18N
        jMenu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_LogoutActionPerformed(evt);
            }
        });
        jMenu_System.add(jMenu_Logout);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu_System.add(jSeparator2);

        jMenu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/edit-delete.png"))); // NOI18N
        jMenu_Exit.setText("Exit");
        jMenu_Exit.setName("jMenu_Exit"); // NOI18N
        jMenu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ExitActionPerformed(evt);
            }
        });
        jMenu_System.add(jMenu_Exit);

        jMenuBar1.add(jMenu_System);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/applications-system.png"))); // NOI18N
        jMenu2.setText("     Edit         ");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/list-resource-add.png"))); // NOI18N
        jMenuItem1.setText("Admin Management");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/document-decrypt.png"))); // NOI18N
        jMenuItem3.setText("Change Password");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/preferences-system.png"))); // NOI18N
        jMenu3.setText("     Setting         ");
        jMenu3.setName("jMenu3"); // NOI18N

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/ooo-base.png"))); // NOI18N
        jMenuItem4.setText("Server Configure");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/kchart.png"))); // NOI18N
        jMenu4.setText("    Reports    ");
        jMenu4.setName("jMenu4"); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/logviewer.png"))); // NOI18N
        jMenuItem7.setText("View Reports");
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/help-browser.png"))); // NOI18N
        jMenu5.setText("    Help          ");
        jMenu5.setName("jMenu5"); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/help-contents.png"))); // NOI18N
        jMenuItem5.setText("Help Content");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu5.add(jSeparator1);

        jAbout.setSelected(true);
        jAbout.setText("About");
        jAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons_24/gtk-about.png"))); // NOI18N
        jAbout.setName("jAbout"); // NOI18N
        jAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutActionPerformed(evt);
            }
        });
        jMenu5.add(jAbout);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dspPerSes(){
       
        Rectangle maxBounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        Point location = maxBounds.getLocation();
        int x = (int) ((maxBounds.getWidth() - getWidth())/2);
        setLocation(x,location.y);
    }
    
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO remove this action
        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exiting();
    }//GEN-LAST:event_formWindowClosing

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
      // new NewJDialog(jPanel1);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jTabbedPane1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTabbedPane1HierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1HierarchyChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
   

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         Runtime rt = Runtime.getRuntime();
        try {
            String filePath = "help.chm";
            rt.exec("hh.exe " + filePath);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot load help file!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ExitActionPerformed
        // TODO add your handling code here:
        exiting();
    }//GEN-LAST:event_jMenu_ExitActionPerformed

    private void jMenu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_LogoutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenu_LogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      new ChangePassDialogGUI(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ServerConfigureGUI(this,false).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutActionPerformed
       new AboutUs(this,false).setVisible(true);
    }//GEN-LAST:event_jAboutActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       new Reporting(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AdminManagementGUI(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                if(permission == 1){
                new MainFrameGUI().setVisible(true);
                
                }
                else{
                new  LoginGUI().setVisible(true);
                }
            }
        });
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_DEPATMENT;
    private javax.swing.JPanel PANEL_EMPLOYEE;
    private javax.swing.JPanel PANEL_LOCATION;
    private javax.swing.JPanel PANEL_PROFILE;
    private javax.swing.JPanel PANEL_PROJECT;
    private javax.swing.JPanel PANEL_ROLE;
    private javax.swing.JPanel PANEL_TRANSFER;
    private javax.swing.JPanel PANEL_WORKITEM;
    private org.jdesktop.swingx.painter.GlossPainter glossPainter1;
    private javax.swing.JCheckBoxMenuItem jAbout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenu_Exit;
    private javax.swing.JMenuItem jMenu_Logout;
    private javax.swing.JMenu jMenu_System;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Department;
    private javax.swing.JPanel jPanel_Employee;
    private javax.swing.JPanel jPanel_Location;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JPanel jPanel_Project;
    private javax.swing.JPanel jPanel_Role;
    private javax.swing.JPanel jPanel_Transfer;
    private javax.swing.JPanel jPanel_workItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private org.jdesktop.swingx.JXHeader jXHeader2;
    private org.jdesktop.swingx.JXHeader jXHeader3;
    private org.jdesktop.swingx.JXHeader jXHeader4;
    private org.jdesktop.swingx.JXHeader jXHeader5;
    private org.jdesktop.swingx.JXHeader jXHeader6;
    private org.jdesktop.swingx.JXHeader jXHeader7;
    private org.jdesktop.swingx.JXHeader jXHeader8;
    private javax.swing.ButtonGroup menuRadioGroup;
    // End of variables declaration//GEN-END:variables
    final private static int permission = 1;
 
  
    
    //ResourceBundle.getBundle(langcode+".properties");
    
     
    
    Connection connected;
    Boolean type;
    String UserName;
    int empID;
   
    
}
